### PR TITLE
OC6 compatibility

### PR DESCRIPTION
**Pull request by butonic**
I ran into problems using editdoc in OC6. This PR moves th tinymce code to the js/css vendor folders, allows installation in an app dir other than `apps` and fixes a js error that prevents further js execution in OC6.

### CODE REVIEW

**Comment by mckaygerhard** [comment]
@butonic hello, this pull du u have working in your own OC instalation? in waht version, oc 6.0.0a or the lasted 6.0.1+ (there's some changes in 6.0.1 that differes from first 6 release)

i installed, and buttons appears, and works, some problems with search lucene and "new" button, said when create edicdoc file has no extension and no creation ocurs

what ist the extension of edicdoc? files

**Comment by mckaygerhard** [comment]
i found the problem, the replace rule are wrong
remove the dot and works event if user write the html extension or not write it

**Comment by butonic** [comment]
glad you found a solution yourself. editdoc is just a wrapper around tinymce, a wysiwyg html editor. So the only filetype you can edit with it is `text/html`. No Idea about the new button ... will have a look ...

**Comment by butonic** [comment]
There is a new problem with the tightened CSP policy in the latest OC6. I have not yet found a solution. Losening the restrictions by overwriting the CSP in config.php seems a bad idea, but tinymce and most other wysiwyg editor seem to rely on the now forbidden magic ...

**Comment by mckaygerhard** [comment]
well in any case, oc6 its the only vrsion that have a powered search of items (serch lucene) but when i install some plugins (includes this) break job chache reindexing... so i have a very crude and simple installation of OC6  >-(

**Comment by mckaygerhard** [comment]
hello @butonic author have recent chages, but i see u already have some also.. 

author seems that made same support but addition with can include own images of users and videos!

du u note the "/" preceding all the call to app path? i remove and try but still not load the build in folders of users..

**Pull request closed without merging**
